packages:
  - codemods-legacy/**
  - tooling-legacy/*

catalog:
  '@ast-grep/cli': ^0.25.4
  '@ast-grep/napi': ^0.25.4
  '@octokit/rest': ^20.0.2
  '@sindresorhus/slugify': ^2.2.1
  '@types/diff': ^5.0.3
  '@types/git-url-parse': ^9.0.3
  '@types/glob': ^8.0.0
  '@types/inquirer': ^9.0.7
  '@types/lodash-es': ^4.17.4
  '@types/parse-github-url': 1.0.3
  '@types/tar': ^6.1.11
  ast-types: ^0.14.2
  colors-cli: ^1.0.33
  detect-indent: ^7.0.1
  detect-newline: ^4.0.1
  diff: ^5.1.0
  filenamify: ^6.0.0
  git-url-parse: ^14.0.0
  glob: ^10.4.5
  inquirer: ^9.2.16
  json-schema-to-typescript: ^13.1.2
  lodash-es: ^4.17.21
  magic-string: ^0.30.10
  mdast-util-from-markdown: ^2.0.0
  mdast-util-mdx: ^3.0.0
  mdast-util-to-markdown: ^2.1.0
  micromark-extension-mdxjs: ^2.0.0
  openai: 4.23.0
  parse-github-url: 1.0.2
  simple-git: ^3.24.0
  tree-kill: ^1.2.2
  ts-invariant: ^0.10.3
  unist-util-visit: ^5.0.0
  valibot: ^0.34.0
  vaul: ^0.9.0
  yaml: ^2.4.5

onlyBuiltDependencies:
  - '@ast-grep/cli'
  - '@biomejs/biome'
  - es5-ext
  - esbuild
